image: node:10
pipelines:
  branches:
    staging:
      - step:
          name: Build app
          script:
            - npm install
            - npm run build
            - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r build/ staging@52.66.202.144:/home/staging/
