export const LOAD_CEREMONY_DETAILS = 'my-project/ceremony/LOAD_CEREMONY_DETAILS';
export const LOAD_CEREMONY_DETAILS_SUCCESS =
  'my-project/ceremony/LOAD_CEREMONY_DETAILS_SUCCESS';
export const LOAD_CEREMONY_DETAILS_FAILURE =
  'my-project/ceremony/LOAD_CEREMONY_DETAILS_FAILURE';

